### ISSUE TITLE
Live 9.5 64bit problems

### ISSUE THREAD

**Issue by Lauchsuppe** [mpiraux/CMD-LC-1-Ableton-9-Control-Surface-Script#1]
Hi!

First, thanks a lot for porting the script to newer Live versions! When I asked the behringer support, they redirected me to your github page. 

I can locate the remotescript in my live preferences (contrary to the official behringer one I tried first) - however, pressing the buttons on my lc1 will only play midi notes and it won't show the red square in my session view. I guess it's the same problem Fabmilan experienced in the other thread. Do you have any idea how I could make it work?

![zuih](https://cloud.githubusercontent.com/assets/9461847/11558006/60eb418c-99b0-11e5-8928-521a26504225.PNG)
[Log.txt](https://github.com/mpiraux/CMD-LC-1-Ableton-9-Control-Surface-Script/files/50670/Log.txt)

**Comment by mpiraux** [comment]
Hi there, and first thanks for the Log.txt!

Sounds like you're not using my exact version, because your Log.txt is reporting an error which is unconsistent with the current state of my script. In fact, I fixed it in my script.
Moreover, there is a strange syntax error which again is not present in my script. 

Be sure to remove completely the directory containing the script, create one named `CMD_LC1` and drop all the py files from this script there. Actually, Ableton doesn't like surface script directories containing the `-` character, and thus `_` is preferred. I did not name my github repository cleverly, taking this into account.
I'm going to add this to the readme.

Thanks for your contribution anyway.

PS: It's a shame that Berhinger could not do the support themselve, because as the commits can tell, I've modified less than 50 lines to make this work with no knowledge at all from the Ableton API or even Python itself.

**Comment by Lauchsuppe** [comment]
Thanks for your quick response!

I renamed the folder and downloaded the scripts anew (just to make sure) - now it will display the red square. However, the functionality still isn't there. The lc1 behaves just as before in that it only triggers midi notes. Maybe I'm overlooking something basic? I'm a total beginner when it comes to remote scripts and setting up midi devices.
[Log.txt](https://github.com/mpiraux/CMD-LC-1-Ableton-9-Control-Surface-Script/files/51355/Log.txt)

**Comment by mpiraux** [comment]
This could be similar to Fabmilan's issue. Because according to the log, the script is initializing fine and is not reporting any error. He experienced the same problem as you are know, but didn't change a thing and suddenly everything was working.
I must say I'm not a big expert of midi mappings but the `Track` button is deactivated for output and input in my configuration. Maybe changing the `Takeover Mode` (`Abhol-Modus`) in your case to `None` will help.
Definitely looking like the script isn't getting any midi signal because Ableton is keeping all for himself.

**Comment by mpiraux** [comment]
I'm closing this issue due to inactivity since 1 month. Feel free to re-open it if you have news about your problem and if you think it's related to the script.

**Comment by Lauchsuppe** [comment]
Hi! Sorry I didn't respond earlier. Something got in the way and had me busy with other stuff. Anyway, today I was free and tried to get my LC1 working - sadly still without success. What I forgot to mention earlier was that I used the cmd channel changer from the behringer website on my lc1 device. Currently, the lc1's midi channel is set to 7. Could that cause any problems? Is there a specific channel I have to set my device to? Other than that, my problem is still there; the remote script won't do anything, but if I enable "Track" the lc1's inputs will be recognized by live.

**Comment by mpiraux** [comment]
Yep definitely! 
Midi channel is actually hardcoded into the script. But you can see [here](https://github.com/mpiraux/CMD-LC-1-Ableton-9-Control-Surface-Script/blob/master/LC1.py#L40) that it's defaulted to 7. The comment next to the line is quite confusing as it states 0 is for early prototypes and 8 is for production model. The Behringer midi changer software changes the channel from 1 to 16. But in reality, midi channels are numbered from 0 to 15.
So if you changed the LC-1 for channel 7 on the software, the script is not receiving the data transmitted because the controller is in fact sending on channel 6. 

You have two options then: 
- Changing back to channel 8 in the software.
- Or change the value in the script by simply opening it as text file and change the 7 for a 6 in your case.

I'll add this issue to the readme, thank you for your feedback and I hope this will fix your issue.

**Comment by Lauchsuppe** [comment]
IT WORKS! I'm so happy! Thank you so much! Without knowing much about python or how remote scripts work, I had a look at the remote scripts and found the value "7" so I figured if anything it would've been channel 7. But I didn't figure they were named differently in the scripts and channel changer.  Setting it to 8 was the solution! Thank you!!

**Comment by robsongama13** [comment]
hello, is there still time for a help in the cmd lc1 script?
